### ISSUE TITLE
URI encoded parameters don't work with gorilla/mux

### ISSUE THREAD

**Issue by cmbrose** [lighthouse-isu/lighthouse#30]
For reference see [the issue in gorrila/mux](https://github.com/gorilla/mux/issues/77)

Even with encoded requests, mux _still_ splits the parameters on `/`s.  For right now we can continue using aliases to get around it, just don't make aliases with forward slashes in them ;)

@chfogerty @theMagicalKarp do you have opinions/thoughts on solutions?  It would be nice to not have to drop mux this late in the game, but this is pretty big.

**Comment by chfogerty** [comment]
The current workaround is to use query parameters.

**Comment by nickmonad** [comment]
For the sake of transparency and as per Chris, Caleb, and I's discussion, I think sticking major routing parameters in the query params should be a last resort

**Comment by nickmonad** [comment]
Limiting the characters used in host aliases would be another option. Client side validation would be straightforward (but of course would have to be checked again server side)

**Comment by cmbrose** [comment]
@theMagicalKarp for beacon you used a different routing library.  Do you think that's something we could switch to if we need to?

I'm not a fan of relying purely on aliasing for this, but I agree with Nick too that query parameters isn't a great thing either.

**Comment by robertsheehy-wf** [comment]
Are you guys talking about where slashes for the docker request are encoded out?

```
some.beacon.ip/d/some.vm.ip/v1.4/_ping
to
some.beacon.ip/d/some.vm.ip%2Fv1.4%2F_ping
```

Because both are valid in beacon. Right now I'm using [goji](https://goji.io/) and I :heart: it.

Not that I'm saying we should change the standard now, but this is kinda why I liked having every request be a `POST` detailing how lighthouse should make the request.

```
POST /docker
{
    "method": "GET",
    "url": "/v1.4/_ping",
    "vm": "127.0.0.1:2375",
    "body": {"someAwesome": "json", "or": "query params"},
    "metadata": "extra stuff that lighthouse can use"
}
```

**Comment by cmbrose** [comment]
@robertsheehy-wf yeah, with gorilla/mux the encoding is resolved before the routing for some reason so there's basically no point to it...

How tough would it be to move to goji do you think?

**Comment by robertsheehy-wf** [comment]
It's hard to say.  We have a lot of code that's coupled with gorilla. The pattern of ...

``` Go
func handler(w http.ResponseWriter, r *http.Request) {
```

is pretty consistent among Go web frameworks though.

**Comment by cmbrose** [comment]
Solved with https://github.com/lighthouse/lighthouse/pull/35
